In [1]:
ckpt= '/eastdata/multi_percep_epoch47.ckpt'

In [2]:
import torch
checkpoint = torch.load(ckpt, map_location=torch.device('cuda'))


/opt/conda/lib/python3.10/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [12]:
sd=checkpoint['state_dict']

In [14]:
re_sd={
    k.replace('model.', ''): v 
    for k, v in sd.items() 
    if 'rgbGAN' not in k
}


In [15]:
from models.autoencoder.autoencoder import AutoEncoder
model=AutoEncoder(in_dim=6, out_dim=3, relu=False)

In [17]:
model.load_state_dict(re_sd)

<All keys matched successfully>

In [1]:
# load pickle file
import pickle
with open('params.pkl', 'rb') as f:
    params = pickle.load(f)

/opt/conda/lib/python3.10/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
params[0]

[('model.modality_preprocessors.event.cls_token',
  Parameter containing:
  tensor([[[-0.2058,  0.2923, -0.0113,  ..., -0.0631, -0.2529,  0.1733]]]),
  False,
  tensor([[[-0.2058,  0.2923, -0.0113,  ..., -0.0631, -0.2529,  0.1733]]])),
 ('model.modality_preprocessors.event.rgbt_stem.proj.1.weight',
  Parameter containing:
  tensor([[[[[-8.2502e-03, -1.5200e-02, -2.0464e-02,  ...,  1.1408e-02,
               9.6196e-03,  3.1156e-03],
             [ 3.0199e-03, -1.6573e-03, -1.2272e-02,  ...,  1.7792e-02,
               1.1809e-02,  5.3399e-03],
             [ 5.2251e-03, -3.4155e-04, -1.2812e-02,  ...,  5.7184e-03,
               4.4938e-03,  1.6608e-04],
             ...,
             [ 1.1505e-02,  1.2100e-02,  6.5771e-03,  ..., -9.7856e-03,
              -6.8601e-04,  3.2187e-03],
             [ 3.6549e-03,  3.8163e-04, -1.7516e-03,  ..., -1.2235e-02,
              -5.2878e-03, -5.8037e-04],
             [ 1.2360e-03, -2.5508e-03, -2.2314e-03,  ..., -1.3280e-02,
              -6.0386

In [3]:
params[1]

[('model.modality_preprocessors.vision.cls_token',
  Parameter containing:
  tensor([[[-0.2058,  0.2923, -0.0113,  ..., -0.0631, -0.2529,  0.1733]]]),
  False,
  tensor([[[-0.2058,  0.2923, -0.0113,  ..., -0.0631, -0.2529,  0.1733]]])),
 ('model.modality_preprocessors.vision.rgbt_stem.proj.1.weight',
  Parameter containing:
  tensor([[[[[-8.2502e-03, -1.5200e-02, -2.0464e-02,  ...,  1.1408e-02,
               9.6196e-03,  3.1156e-03],
             [ 3.0199e-03, -1.6573e-03, -1.2272e-02,  ...,  1.7792e-02,
               1.1809e-02,  5.3399e-03],
             [ 5.2251e-03, -3.4155e-04, -1.2812e-02,  ...,  5.7184e-03,
               4.4938e-03,  1.6608e-04],
             ...,
             [ 1.1505e-02,  1.2100e-02,  6.5771e-03,  ..., -9.7856e-03,
              -6.8601e-04,  3.2187e-03],
             [ 3.6549e-03,  3.8163e-04, -1.7516e-03,  ..., -1.2235e-02,
              -5.2878e-03, -5.8037e-04],
             [ 1.2360e-03, -2.5508e-03, -2.2314e-03,  ..., -1.3280e-02,
              -6.03

In [7]:
params[0][-1][-1]==params[1][-1][-1]

tensor([[True, True, True,  ..., True, True, True],
        [True, True, True,  ..., True, True, True],
        [True, True, True,  ..., True, True, True],
        ...,
        [True, True, True,  ..., True, True, True],
        [True, True, True,  ..., True, True, True],
        [True, True, True,  ..., True, True, True]])

In [3]:
# load pickle file
import pickle
with open('event_params.pkl', 'rb') as f:
    params = pickle.load(f)

In [4]:
params

[('model.modality_preprocessors.event.cls_token', False),
 ('model.modality_preprocessors.event.rgbt_stem.proj.1.weight', False),
 ('model.modality_preprocessors.event.pos_embedding_helper.pos_embed', False),
 ('model.modality_trunks.event.pre_transformer_layer.0.weight', True),
 ('model.modality_trunks.event.pre_transformer_layer.0.bias', True),
 ('model.modality_trunks.event.blocks.0.attn.in_proj_weight', True),
 ('model.modality_trunks.event.blocks.0.attn.in_proj_bias', True),
 ('model.modality_trunks.event.blocks.0.attn.out_proj.weight', True),
 ('model.modality_trunks.event.blocks.0.attn.out_proj.bias', True),
 ('model.modality_trunks.event.blocks.0.norm_1.weight', True),
 ('model.modality_trunks.event.blocks.0.norm_1.bias', True),
 ('model.modality_trunks.event.blocks.0.mlp.fc1.weight', True),
 ('model.modality_trunks.event.blocks.0.mlp.fc1.bias', True),
 ('model.modality_trunks.event.blocks.0.mlp.fc2.weight', True),
 ('model.modality_trunks.event.blocks.0.mlp.fc2.bias', True),
 

In [2]:
pip install colorizers

ERROR: Could not find a version that satisfies the requirement colorizers (from versions: none)
ERROR: No matching distribution found for colorizers
Note: you may need to restart the kernel to use updated packages.
